#! /bin/bash

# echo $(( ($(date +%s) - $(date --date="Jul 20, 1969" +%s) )/(60*60*24) ))

i=0
while [ -n "$1" ]; do
    D=""
    case $1 in
	'-s')
	    ;;
	now|NOW|Now)
	    DATE[$i]=""
	    ;;
	*)
	    DATE[$i]="$1"
	    D="--date"
	    ;;
    esac
    (( i++ ))
    shift
done

DELTAtm=$(( ($(date $D "${DATE[0]}" +%s) - $(date $D "${DATE[1]}" +%s)) / (60*60*24) ))

echo $DELTAtm
